### ISSUE TITLE
imu_link tf should not be child of odom

### ISSUE THREAD

**Issue by pitosalas** [hippo5329/linorobot2_hardware#52]
This is a pretty subtle issue that I've spent a bit of time trying to solve. I think I got this diagnosis correct but I am not 100% sure.

I was working to locate where I can flip the IMU TF over so that it aligns with my robot build.  I have found (without modifying anything---I think) that the imu_link tf is a child of odom which is incorrect. You can see that here:

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/2586bbb1-e60e-4a20-93e4-e15268ccb95e" />

Now this only seems to happen when I enable the magnetometer fusion. In other words, running

`ros2 launch linorobott2/bringup bringup.xxxx
`

It comes up correctly as a child of base_link. However when I look in Rviz, the tf is not changing at all that is it is not being controlled by the imu.

Once I enable Madgwick as required:

```
launch:
  - include:
      file: "$(find-pkg-share linorobot2_bringup)/launch/bringup.launch.py"
      arg:
        - name: base_serial_port
          value: "/dev/ttyUSB0"
        - name: micro_ros_baudrate
          value: "921600"
        - name: madgwick
          value: "true"
        - name: orientatoin_stddev
          value: "0.01"

```

<img width="454" alt="Image" src="https://github.com/user-attachments/assets/e4d4c5ca-bef5-4176-b90d-9ab404f83ba4" />

Three things happen:

1) The IMU in RVIZ is "alive" and responds to movement
2) The IMU tf is now child of odom
3) And the IMU has the z axis pointing down, which is as expected because my gendrv board is mounted on top of the board (this is true for /imu/data_raw but /imu/data has it right side up (see image.)

So the question is, which node is publishing updates to the tf for /imu_base? Because it is setting the parent to /odom and also how can I change its orientation to account for my placement of the gendrv board.

Have you gone this deep into these issues?
